"use client";
import {FormEvent,useMemo,useState} from "react";
import {adminDeactivateMachine,adminDeactivateOperator,adminDeleteOrder,adminDeletePoint,adminSetOrderClosed,adminUpdateOrder,adminUpdatePoint,adminUpdateUser,Maquina,Ordem,Perfil,updateMachine} from "./supabase";
import {factoryDateTimeInput,factoryInputToIso,formatFactoryDateTime} from "./factory-time";
type Props={orders:Ordem[];profiles:Perfil[];machines:Maquina[];token:string;onRefresh:()=>Promise<void>;onClose:()=>void};
type Tab="orders"|"points"|"operators"|"machines";
type Editor={kind:"order"|"orderStatus"|"point"|"operator"|"machine";id:string;title:string;values:Record<string,string>};
type Confirmation={title:string;description:string;action:()=>Promise<unknown>;success:string};
const localDate=factoryDateTimeInput;
const norm=(value:unknown)=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleUpperCase("pt-BR");
export function AdminScreen({orders:rawOrders,profiles,machines,token,onRefresh,onClose}:Props){
 const [tab,setTab]=useState<Tab>("orders"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[editor,setEditor]=useState<Editor|null>(null),[confirmation,setConfirmation]=useState<Confirmation|null>(null);
 const [search,setSearch]=useState(""),[orderStatus,setOrderStatus]=useState("all"),[createdFrom,setCreatedFrom]=useState(""),[createdTo,setCreatedTo]=useState("");
 const orders=useMemo(()=>rawOrders.map(order=>({...order,artigo:`${order.codigo_artigo||"SEM CÓDIGO"} - ${order.artigo}`})),[rawOrders]);
 const points=useMemo(()=>orders.flatMap(order=>(order.operacoes??[]).flatMap(operation=>(operation.apontamentos??[]).map(point=>({point,order,operation})))),[orders]);
 const term=norm(search);
 const filteredOrders=orders.filter(order=>{const open=(order.operacoes??[]).some(operation=>operation.apontamentos?.some(point=>!point.termino_em));const date=order.criado_em?.slice(0,10)??"";const statusOk=orderStatus==="all"||(orderStatus==="closed"&&!!order.encerrada_em)||(orderStatus==="running"&&open)||(orderStatus==="cancelled"&&order.status==="cancelada")||(orderStatus==="active"&&!order.encerrada_em&&order.status!=="cancelada");return norm([order.numero_op,order.artigo,order.cliente,order.nf_entrada].join(" ")).includes(term)&&statusOk&&(!createdFrom||date>=createdFrom)&&(!createdTo||date<=createdTo)});
 const filteredPoints=points.filter(item=>norm([item.order.numero_op,item.order.artigo,item.operation.codigo,item.operation.descricao,profiles.find(p=>p.id===item.point.operador_id)?.nome,machines.find(m=>m.id===item.point.maquina_id)?.codigo,item.point.observacao].join(" ")).includes(term));
 const filteredProfiles=profiles.filter(profile=>norm([profile.nome,profile.perfil].join(" ")).includes(term));
 const filteredMachines=machines.filter(machine=>norm([machine.codigo,machine.nome,machine.setor].join(" ")).includes(term));
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setMessage("");try{await action();await onRefresh();setEditor(null);setConfirmation(null);setMessage(success)}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível concluir.")}finally{setBusy(false)}}
 function change(name:string,value:string){setEditor(current=>current?{...current,values:{...current.values,[name]:value}}:current)}
 async function save(event:FormEvent){event.preventDefault();if(!editor)return;const v=editor.values;
  if(editor.kind==="order")await run(()=>adminUpdateOrder(token,{id:editor.id,numero:v.numero,cliente:v.cliente,artigo:v.artigo.replace(/^(?:\d{6}|SEM CÓDIGO)\s*-\s*/i,"")}),"OP atualizada.");
  if(editor.kind==="orderStatus")await run(()=>adminSetOrderClosed(token,editor.id,v.encerrar==="true",v.motivo),v.encerrar==="true"?"OP encerrada.":"OP reaberta.");
  if(editor.kind==="operator")await run(()=>adminUpdateUser(token,editor.id,v.nome,v.perfil as "admin"|"operador"),"Usuário atualizado.");
  if(editor.kind==="machine")await run(()=>updateMachine(token,editor.id,{codigo:v.codigo,nome:v.nome,setor:v.setor}),"Máquina atualizada.");
  if(editor.kind==="point")await run(()=>adminUpdatePoint(token,{id:editor.id,operatorId:v.operador,machineId:v.maquina,start:factoryInputToIso(v.inicio),end:v.termino?factoryInputToIso(v.termino):null,note:v.observacao}),"Apontamento atualizado.");
 }
 const confirm=(title:string,description:string,action:()=>Promise<unknown>,success:string)=>setConfirmation({title,description,action,success});
 return <section className="admin-screen"><header><div><p className="eyebrow">ACESSO RESTRITO</p><h2>Administração</h2><p>Correção, permissões e exclusão de registros.</p></div><button onClick={onClose}>×</button></header>
 <nav>{([['orders','OPs'],['points','Apontamentos'],['operators','Usuários'],['machines','Máquinas']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>{setTab(id);setSearch("")}}>{label}</button>)}</nav><div className="admin-filters"><label className="admin-search">PESQUISAR<input value={search} onChange={event=>setSearch(event.target.value)} placeholder={tab==="orders"?"OP, artigo, cliente ou NF":tab==="points"?"OP, operação, operador, máquina ou observação":tab==="operators"?"Nome ou nível de acesso":"Código, máquina ou setor"}/></label>{tab==="orders"&&<><label>SITUAÇÃO<select value={orderStatus} onChange={event=>setOrderStatus(event.target.value)}><option value="all">Todas</option><option value="active">Ativas</option><option value="running">Em execução</option><option value="closed">Encerradas</option><option value="cancelled">Canceladas</option></select></label><label>CRIADA DE<input type="date" value={createdFrom} onChange={event=>setCreatedFrom(event.target.value)}/></label><label>ATÉ<input type="date" value={createdTo} onChange={event=>setCreatedTo(event.target.value)}/></label></>}</div>{message&&<p className="admin-message">{message}</p>}
 <div className="admin-list" aria-busy={busy}>
{tab==="orders"&&filteredOrders.map(order=><article key={order.id}><div><b>OP {order.numero_op}</b><span>{order.cliente}</span><small>{order.artigo} · {order.status==="cancelada"?"CANCELADA":order.encerrada_em?"ENCERRADA":"ATIVA"}</small></div><div><button disabled={busy} onClick={()=>setEditor({kind:"order",id:order.id,title:`Editar OP ${order.numero_op}`,values:{numero:order.numero_op,cliente:order.cliente,artigo:order.artigo}})}>Editar</button><button className={order.encerrada_em?"":"danger"} disabled={busy} onClick={()=>setEditor({kind:"orderStatus",id:order.id,title:order.encerrada_em?`Reabrir OP ${order.numero_op}`:`Encerrar OP ${order.numero_op}`,values:{encerrar:order.encerrada_em?"false":"true",motivo:""}})}>{order.encerrada_em?"Reabrir":"Encerrar"}</button><button className="danger" disabled={busy} onClick={()=>confirm(`Excluir OP ${order.numero_op}?`,"A OP, suas operações e apontamentos serão excluídos definitivamente.",()=>adminDeleteOrder(token,order.id),"OP excluída.")}>Excluir</button></div></article>)}
{tab==="points"&&filteredPoints.map(item=><article key={item.point.id}><div><b>OP {item.order.numero_op} · {item.operation.codigo}</b><span>{profiles.find(p=>p.id===item.point.operador_id)?.nome??"Operador"} · {machines.find(m=>m.id===item.point.maquina_id)?.codigo??"Máquina"}</span><small>{formatFactoryDateTime(item.point.inicio_em)} → {formatFactoryDateTime(item.point.termino_em,"em andamento")}</small></div><div><button disabled={busy} onClick={()=>setEditor({kind:"point",id:item.point.id,title:`Editar apontamento · OP ${item.order.numero_op}`,values:{operador:item.point.operador_id,maquina:item.point.maquina_id,inicio:localDate(item.point.inicio_em),termino:localDate(item.point.termino_em),observacao:item.point.observacao??""}})}>Editar</button><button className="danger" disabled={busy} onClick={()=>confirm("Excluir apontamento?","O registro será removido e a operação recalculada.",()=>adminDeletePoint(token,item.point.id),"Apontamento excluído.")}>Excluir</button></div></article>)}
{tab==="operators"&&filteredProfiles.map(profile=><article key={profile.id}><div><b>{profile.nome}</b><span>{profile.perfil==="admin"?"Administrador":"Produção"}</span></div><div><button disabled={busy} onClick={()=>setEditor({kind:"operator",id:profile.id,title:"Editar usuário",values:{nome:profile.nome,perfil:profile.perfil==="admin"?"admin":"operador"}})}>Editar</button><button className="danger" disabled={busy||profile.perfil==="admin"} onClick={()=>confirm(`Desativar ${profile.nome}?`,"O acesso será bloqueado, mas o histórico será preservado.",()=>adminDeactivateOperator(token,profile.id),"Usuário desativado.")}>Desativar</button></div></article>)}
{tab==="machines"&&filteredMachines.map(machine=><article key={machine.id}><div><b>{machine.codigo} · {machine.nome}</b><span>{machine.setor||"Sem setor"}</span></div><div><button disabled={busy} onClick={()=>setEditor({kind:"machine",id:machine.id,title:"Editar máquina",values:{codigo:machine.codigo,nome:machine.nome,setor:machine.setor??""}})}>Editar</button><button className="danger" disabled={busy} onClick={()=>confirm(`Desativar ${machine.codigo}?`,"A máquina deixará de aparecer nos novos apontamentos; o histórico será preservado.",()=>adminDeactivateMachine(token,machine.id),"Máquina desativada.")}>Desativar</button></div></article>)}
{((tab==="orders"&&!filteredOrders.length)||(tab==="points"&&!filteredPoints.length)||(tab==="operators"&&!filteredProfiles.length)||(tab==="machines"&&!filteredMachines.length))&&<p className="admin-empty">Nenhum resultado encontrado para os filtros informados.</p>}
 </div>
 {editor&&<div className="admin-dialog-backdrop" onMouseDown={()=>setEditor(null)}><form className="admin-dialog" onSubmit={save} onMouseDown={event=>event.stopPropagation()}><header><div><p className="eyebrow">EDIÇÃO</p><h3>{editor.title}</h3></div><button type="button" onClick={()=>setEditor(null)}>×</button></header>
 {editor.kind==="order"&&<><label>Número da OP<input required value={editor.values.numero} onChange={e=>change("numero",e.target.value)}/></label><label>Cliente<input required value={editor.values.cliente} onChange={e=>change("cliente",e.target.value)}/></label><label>Artigo<input required value={editor.values.artigo} onChange={e=>change("artigo",e.target.value)}/></label></>}
 {editor.kind==="orderStatus"&&<><p>{editor.values.encerrar==="true"?"Depois de encerrada, nenhum operador poderá iniciar apontamentos nesta OP.":"A OP voltará a aceitar novas execuções, preservando todo o histórico."}</p><label>Motivo<textarea required minLength={3} rows={3} value={editor.values.motivo} onChange={e=>change("motivo",e.target.value)} placeholder="Informe o motivo para a auditoria"/></label></>}
 {editor.kind==="operator"&&<><label>Nome do usuário<input required value={editor.values.nome} onChange={e=>change("nome",e.target.value)}/></label><label>Nível de acesso<select value={editor.values.perfil} onChange={e=>change("perfil",e.target.value)}><option value="operador">Produção</option><option value="admin">Administrador</option></select></label></>}
 {editor.kind==="machine"&&<><label>Código<input required value={editor.values.codigo} onChange={e=>change("codigo",e.target.value)}/></label><label>Nome<input required value={editor.values.nome} onChange={e=>change("nome",e.target.value)}/></label><label>Setor<input value={editor.values.setor} onChange={e=>change("setor",e.target.value)}/></label></>}
 {editor.kind==="point"&&<><div className="admin-form-grid"><label>Operador<select required value={editor.values.operador} onChange={e=>change("operador",e.target.value)}>{profiles.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label>Máquina<select required value={editor.values.maquina} onChange={e=>change("maquina",e.target.value)}>{machines.map(m=><option key={m.id} value={m.id}>{m.codigo} · {m.nome}</option>)}</select></label><label>Data e hora de início<input type="datetime-local" required value={editor.values.inicio} onChange={e=>change("inicio",e.target.value)}/></label><label>Data e hora de término<input type="datetime-local" value={editor.values.termino} onChange={e=>change("termino",e.target.value)}/></label></div><label>Observação<textarea rows={3} value={editor.values.observacao} onChange={e=>change("observacao",e.target.value)}/></label></>}
 <footer><button type="button" onClick={()=>setEditor(null)}>Cancelar</button><button className="save" disabled={busy}>{busy?"Salvando…":"Salvar alterações"}</button></footer></form></div>}
 {confirmation&&<div className="admin-dialog-backdrop" onMouseDown={()=>setConfirmation(null)}><section className="admin-dialog confirm-dialog" onMouseDown={event=>event.stopPropagation()}><span className="warning-icon">!</span><h3>{confirmation.title}</h3><p>{confirmation.description}</p><footer><button onClick={()=>setConfirmation(null)}>Cancelar</button><button className="delete" disabled={busy} onClick={()=>run(confirmation.action,confirmation.success)}>{busy?"Excluindo…":"Confirmar"}</button></footer></section></div>}
 </section>
}
