"use client";
import {useMemo,useState} from "react";
import {adminDeactivateMachine,adminDeactivateOperator,adminDeleteOrder,adminDeletePoint,adminUpdateOperator,adminUpdateOrder,adminUpdatePoint,Maquina,Ordem,Perfil,updateMachine} from "./supabase";

type Props={orders:Ordem[];profiles:Perfil[];machines:Maquina[];token:string;onRefresh:()=>Promise<void>;onClose:()=>void};
type Tab="orders"|"points"|"operators"|"machines";
const ask=(label:string,value:string)=>window.prompt(label,value)?.trim();
export function AdminScreen({orders,profiles,machines,token,onRefresh,onClose}:Props){
 const [tab,setTab]=useState<Tab>("orders");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const points=useMemo(()=>orders.flatMap(order=>(order.operacoes??[]).flatMap(operation=>(operation.apontamentos??[]).map(point=>({point,order,operation})))),[orders]);
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setMessage("");try{await action();await onRefresh();setMessage(success)}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível concluir.")}finally{setBusy(false)}}
 async function editOrder(order:Ordem){const numero=ask("Número da OP",order.numero_op);if(!numero)return;const cliente=ask("Cliente",order.cliente);if(cliente===undefined)return;const artigo=ask("Artigo",order.artigo);if(artigo===undefined)return;await run(()=>adminUpdateOrder(token,{id:order.id,numero,cliente,artigo}),"OP atualizada.")}
 async function editOperator(profile:Perfil){const name=ask("Nome do operador",profile.nome);if(!name)return;await run(()=>adminUpdateOperator(token,profile.id,name),"Operador atualizado.")}
 async function editMachine(machine:Maquina){const codigo=ask("Código da máquina",machine.codigo);if(!codigo)return;const nome=ask("Nome da máquina",machine.nome);if(!nome)return;const setor=ask("Setor",machine.setor??"");if(setor===undefined)return;await run(()=>updateMachine(token,machine.id,{codigo,nome,setor}),"Máquina atualizada.")}
 async function editPoint(item:(typeof points)[number]){const operatorName=ask("Operador",profiles.find(p=>p.id===item.point.operador_id)?.nome??"");if(!operatorName)return;const machineCode=ask("Código da máquina",machines.find(m=>m.id===item.point.maquina_id)?.codigo??"");if(!machineCode)return;const operator=profiles.find(p=>p.nome.toLocaleUpperCase("pt-BR")===operatorName.toLocaleUpperCase("pt-BR"));const machine=machines.find(m=>m.codigo.toLocaleUpperCase("pt-BR")===machineCode.toLocaleUpperCase("pt-BR"));if(!operator||!machine){setMessage("Operador ou máquina não encontrado.");return}const start=ask("Início (data e hora ISO)",item.point.inicio_em);if(!start)return;const end=ask("Término (vazio para apontamento aberto)",item.point.termino_em??"");if(end===undefined)return;const note=ask("Observação",item.point.observacao??"");if(note===undefined)return;await run(()=>adminUpdatePoint(token,{id:item.point.id,operatorId:operator.id,machineId:machine.id,start,end:end||null,note}),"Apontamento atualizado.")}
 const remove=(question:string,action:()=>Promise<unknown>,success:string)=>{if(window.confirm(question))void run(action,success)};
 return <section className="admin-screen"><header><div><p className="eyebrow">ACESSO RESTRITO</p><h2>Administração</h2><p>Correção e exclusão de cadastros e registros.</p></div><button onClick={onClose}>×</button></header><nav>{([['orders','OPs'],['points','Apontamentos'],['operators','Operadores'],['machines','Máquinas']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>{message&&<p className="admin-message">{message}</p>}<div className="admin-list" aria-busy={busy}>{tab==="orders"&&orders.map(order=><article key={order.id}><div><b>OP {order.numero_op}</b><span>{order.cliente}</span><small>{order.artigo}</small></div><div><button disabled={busy} onClick={()=>editOrder(order)}>Editar</button><button className="danger" disabled={busy} onClick={()=>remove(`Excluir definitivamente a OP ${order.numero_op} e todos os seus apontamentos?`,()=>adminDeleteOrder(token,order.id),"OP excluída.")}>Excluir</button></div></article>)}{tab==="points"&&points.map(item=><article key={item.point.id}><div><b>OP {item.order.numero_op} · {item.operation.codigo}</b><span>{profiles.find(p=>p.id===item.point.operador_id)?.nome??"Operador"} · {machines.find(m=>m.id===item.point.maquina_id)?.codigo??"Máquina"}</span><small>{new Date(item.point.inicio_em).toLocaleString("pt-BR")} → {item.point.termino_em?new Date(item.point.termino_em).toLocaleString("pt-BR"):"em andamento"}</small></div><div><button disabled={busy} onClick={()=>editPoint(item)}>Editar</button><button className="danger" disabled={busy} onClick={()=>remove("Excluir definitivamente este apontamento?",()=>adminDeletePoint(token,item.point.id),"Apontamento excluído.")}>Excluir</button></div></article>)}{tab==="operators"&&profiles.map(profile=><article key={profile.id}><div><b>{profile.nome}</b><span>{profile.perfil}</span></div><div><button disabled={busy} onClick={()=>editOperator(profile)}>Editar</button><button className="danger" disabled={busy||profile.perfil==="admin"} onClick={()=>remove(`Desativar o operador ${profile.nome}?`,()=>adminDeactivateOperator(token,profile.id),"Operador desativado.")}>Desativar</button></div></article>)}{tab==="machines"&&machines.map(machine=><article key={machine.id}><div><b>{machine.codigo} · {machine.nome}</b><span>{machine.setor||"Sem setor"}</span></div><div><button disabled={busy} onClick={()=>editMachine(machine)}>Editar</button><button className="danger" disabled={busy} onClick={()=>remove(`Desativar a máquina ${machine.codigo}?`,()=>adminDeactivateMachine(token,machine.id),"Máquina desativada.")}>Desativar</button></div></article>)}{((tab==="orders"&&!orders.length)||(tab==="points"&&!points.length)||(tab==="operators"&&!profiles.length)||(tab==="machines"&&!machines.length))&&<p className="admin-empty">Nenhum registro encontrado.</p>}</div></section>}
