"use client";
import {useEffect,useMemo,useState} from "react";
import {Maquina,Ordem,saveSession} from "./supabase";
import {ArticleLabel} from "./article-label";
import {deadlineStatus,formatDateOnly} from "./deadline";
import {formatFactoryDateTime} from "./factory-time";

const MONTHS=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const isoDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const monthBounds=(year:number,month:number)=>({from:isoDate(new Date(year,month,1)),to:isoDate(new Date(year,month+1,0))});
const norm=(value:unknown)=>String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleUpperCase("pt-BR");

export function ClientPortal({orders,machines,userName,onRefresh,onLogout}:{orders:Ordem[];machines:Maquina[];userName:string;onRefresh:()=>Promise<void>;onLogout:()=>void}){
 const today=new Date(),initial=monthBounds(today.getFullYear(),today.getMonth());const [search,setSearch]=useState(""),[status,setStatus]=useState("all"),[deadline,setDeadline]=useState("all"),[month,setMonth]=useState(today.getMonth()),[year,setYear]=useState(today.getFullYear()),[from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[refreshing,setRefreshing]=useState(false),[updated,setUpdated]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>refresh(),60000);return()=>clearInterval(timer)},[]);
 async function refresh(){setRefreshing(true);try{await onRefresh();setUpdated(Date.now())}finally{setRefreshing(false)}}
 function chooseMonth(nextMonth:number,nextYear=year){setMonth(nextMonth);setYear(nextYear);const range=monthBounds(nextYear,nextMonth);setFrom(range.from);setTo(range.to)}
 const prepared=useMemo(()=>orders.map(order=>{const operations=[...(order.operacoes??[])].sort((a,b)=>a.sequencia-b.sequencia);const points=operations.flatMap(operation=>(operation.apontamentos??[]).map(point=>({operation,point})));const open=points.find(item=>!item.point.termino_em);const covered=operations.filter(operation=>operation.apontamentos?.some(point=>point.termino_em)).length;const progress=operations.length?Math.round(covered/operations.length*100):0;const delivery=deadlineStatus(order);return{order,operations,open,progress,delivery}}),[orders]);
 const term=norm(search);const filtered=prepared.filter(({order,open,delivery})=>{const date=order.data_op??order.criado_em?.slice(0,10)??"";const state=order.encerrada_em?"closed":open?"running":order.status==="aguardando"?"waiting":"production";return(!term||norm([order.numero_op,order.nf_entrada,order.codigo_artigo,order.artigo].join(" ")).includes(term))&&(status==="all"||status===state)&&(deadline==="all"||deadline===delivery.key)&&(!from||date>=from)&&(!to||date<=to)});
 const running=prepared.filter(item=>item.open).length,closed=prepared.filter(item=>item.order.encerrada_em).length,late=prepared.filter(item=>item.delivery.key==="late").length,meters=filtered.reduce((sum,item)=>sum+Number(item.order.metros??0),0);
 function clear(){setSearch("");setStatus("all");setDeadline("all");chooseMonth(today.getMonth(),today.getFullYear())}
 return <main className="client-portal"><header className="client-header"><div className="client-brand"><span>IP</span><div><b>Ibirapuera</b><small>Portal PCP Matriz</small></div></div><div className="client-user"><span><b>{userName}</b><small>IBIRAPUERA TEXTIL LTDA</small></span><button onClick={onLogout}>Sair</button></div></header><section className="client-content"><div className="client-title"><div><p className="eyebrow">ACOMPANHAMENTO DE PEDIDOS</p><h1>Ordens de produção</h1><p>Posição atual dos pedidos da Ibirapuera Têxtil.</p></div><div><small>Atualizado {new Date(updated).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small><button disabled={refreshing} onClick={refresh}>{refreshing?"Atualizando…":"↻ Atualizar"}</button></div></div>
 <div className="client-kpis"><article><small>OPs encontradas</small><strong>{prepared.length}</strong><span>Base completa do cliente</span></article><article className="blue"><small>Em execução agora</small><strong>{running}</strong><span>Com apontamento aberto</span></article><article className="red"><small>Pedidos atrasados</small><strong>{late}</strong><span>OPs abertas fora do prazo</span></article><article className="green"><small>Encerradas</small><strong>{closed}</strong><span>Pedidos concluídos</span></article><article><small>Metros filtrados</small><strong>{meters.toLocaleString("pt-BR")}</strong><span>No período selecionado</span></article></div>
 <div className="client-filters"><label className="client-search">PESQUISAR<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Número da OP, NF de entrada, código ou artigo"/></label><label>MÊS<select value={month} onChange={event=>chooseMonth(Number(event.target.value))}>{MONTHS.map((name,index)=><option key={name} value={index}>{name}</option>)}</select></label><label>ANO<select value={year} onChange={event=>chooseMonth(month,Number(event.target.value))}>{Array.from({length:7},(_,index)=>today.getFullYear()-5+index).map(value=><option key={value}>{value}</option>)}</select></label><label>DATA OP — DE<input type="date" value={from} max={to} onChange={event=>setFrom(event.target.value)}/></label><label>ATÉ<input type="date" value={to} min={from} onChange={event=>setTo(event.target.value)}/></label><label>SITUAÇÃO<select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Todas</option><option value="running">Em execução</option><option value="production">Em produção</option><option value="waiting">Aguardando</option><option value="closed">Encerradas</option></select></label><label>PRAZO<select value={deadline} onChange={event=>setDeadline(event.target.value)}><option value="all">Todos</option><option value="late">Atrasadas</option><option value="today">Entrega hoje</option><option value="soon">Próximos dias</option><option value="on-time">No prazo</option><option value="no-deadline">Sem prazo</option></select></label><button onClick={clear}>Limpar filtros</button></div>
 <div className="client-results"><div className="client-result-count"><b>{filtered.length}</b> OP{filtered.length===1?"":"s"} no resultado</div>{filtered.map(({order,operations,open,progress,delivery})=>{const current=open?.operation??operations.find(operation=>!operation.apontamentos?.some(point=>point.termino_em))??operations.at(-1);const machine=machines.find(item=>item.id===open?.point.maquina_id);return <article className="client-order" key={order.id}><div className="client-order-top"><div><span className="client-op">OP {order.numero_op}</span><span className={`client-status ${order.encerrada_em?"closed":open?"running":"waiting"}`}>{order.encerrada_em?"Encerrada":open?"Em execução":order.status==="aguardando"?"Aguardando":"Em produção"}</span><span className={`deadline-badge ${delivery.key}`}>{delivery.label}</span><ArticleLabel code={order.codigo_artigo} name={order.artigo}/><small>NF entrada: <b>{order.nf_entrada||"não informada"}</b> · Data OP: <b>{formatDateOnly(order.data_op)}</b>{delivery.due&&<> · Entrega estimada: <b>{formatDateOnly(delivery.due)}</b></>}</small></div><div className="client-quantity"><span><small>PEÇAS</small><b>{order.pecas??0}</b></span><span><small>METROS</small><b>{Number(order.metros??0).toLocaleString("pt-BR")}</b></span><span><small>PESO</small><b>{Number(order.peso??0).toLocaleString("pt-BR")}</b></span></div><div className="client-progress"><strong>{progress}%</strong><span>{operations.filter(operation=>operation.apontamentos?.some(point=>point.termino_em)).length}/{operations.length} operações com apontamento</span><i><u style={{width:`${progress}%`}}/></i></div></div><div className="client-current"><div><small>{open?"EM EXECUÇÃO":"POSIÇÃO ATUAL"}</small><b>{current?`${current.codigo} · ${current.descricao}`:"Fluxo não cadastrado"}</b>{open&&<span>{machine?`${machine.codigo} · ${machine.nome}`:"Máquina não informada"} · desde {formatFactoryDateTime(open.point.inicio_em)}</span>}</div></div><div className="client-flow">{operations.map(operation=>{const count=operation.apontamentos?.filter(point=>point.termino_em).length??0;return <span className={operation.status} key={operation.id}><b>{operation.codigo}</b>{operation.descricao}<small>{operation.status==="em_andamento"?"Em andamento":count?"Contém apontamento":"Sem apontamento"}</small></span>})}</div></article>})}{!filtered.length&&<div className="client-empty"><b>Nenhuma OP encontrada</b><span>Altere o período ou os filtros de pesquisa.</span><button onClick={clear}>Limpar filtros</button></div>}</div></section></main>
}
