"use client";
import {KeyboardEvent,useEffect,useMemo,useState} from "react";
import {Apontamento,finishGroupedOperation,Maquina,Ordem,Perfil,startGroupedOperation} from "./supabase";
import {parseOpScan,parseOperationScan} from "./scanner";
import {ArticleLabel} from "./article-label";
type Props={orders:Ordem[];profiles:Perfil[];machines:Maquina[];token:string;userId:string;onRefresh:()=>Promise<void>};
const norm=(v:string)=>v.trim().toLocaleUpperCase("pt-BR");
export function GroupedPointing({orders,profiles,machines,token,userId,onRefresh}:Props){
 const [scan,setScan]=useState("");const [ids,setIds]=useState<string[]>([]);const [code,setCode]=useState("");const [criterion,setCriterion]=useState<"metros"|"peso"|"pecas">("metros");const [quantities,setQuantities]=useState<Record<string,number>>({});const [operatorCode,setOperatorCode]=useState(profiles.find(p=>p.id===userId)?.nome??"");const [machineCode,setMachineCode]=useState("");const [note,setNote]=useState("");const [groupId,setGroupId]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const selected=ids.map(id=>orders.find(o=>o.id===id)).filter((o):o is Ordem=>!!o);
 const common=useMemo(()=>{if(!selected.length)return[];const available=(status:string)=>status!=="em_andamento";const first=selected[0].operacoes??[];return first.filter(op=>available(op.status)&&selected.every(order=>(order.operacoes??[]).some(other=>other.codigo===op.codigo&&available(other.status))))},[selected]);
 const activeGroups=useMemo(()=>{const groups=new Map<string,{id:string;code:string;description:string;points:Array<{order:Ordem;point:Apontamento}>}>();for(const order of orders)for(const operation of order.operacoes??[])for(const point of operation.apontamentos??[])if(point.grupo_id&&!point.termino_em&&point.operador_id===userId){const current=groups.get(point.grupo_id)??{id:point.grupo_id,code:operation.codigo,description:operation.descricao,points:[]};current.points.push({order,point});groups.set(point.grupo_id,current)}return[...groups.values()]},[orders,userId]);
 const operator=profiles.find(p=>norm(p.nome)===norm(operatorCode)||p.id===operatorCode);const machine=machines.find(m=>norm(m.codigo)===norm(machineCode)||norm(m.nome)===norm(machineCode)||m.id===machineCode);
 const quantity=(order:Ordem)=>quantities[order.id]??Number(order[criterion]??0);
 function add(){const number=parseOpScan(scan);const order=orders.find(o=>o.numero_op===number);if(!order){setMessage("OP não encontrada.");return}if(order.encerrada_em){setMessage("Esta OP está encerrada e não pode entrar no grupo.");return}if(ids.includes(order.id)){setMessage("Esta OP já está no grupo.");return}setIds(current=>[...current,order.id]);setScan("");setCode("");setMessage("")}
 function key(event:KeyboardEvent<HTMLInputElement>){if(event.key==="Enter"){event.preventDefault();add()}}
 async function start(){const operationCode=parseOperationScan(code);if(selected.length<2){setMessage("Leia pelo menos duas OPs.");return}if(!operationCode||!common.some(op=>op.codigo===operationCode)){setMessage("Escolha uma operação comum a todas as OPs.");return}if(!operator||!machine){setMessage("Leia um operador e uma máquina válidos.");return}const items=selected.map(order=>({operacao_id:(order.operacoes??[]).find(op=>op.codigo===operationCode)!.id,quantidade:quantity(order)}));if(items.some(item=>item.quantidade<=0)){setMessage("Todas as quantidades precisam ser maiores que zero.");return}setBusy(true);try{const id=await startGroupedOperation(token,{code:operationCode,operatorId:operator.id,machineId:machine.id,criterion,items,note});setGroupId(id);await onRefresh();setMessage("Apontamento agrupado iniciado.")}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível iniciar.")}finally{setBusy(false)}}
 async function finish(){if(!groupId)return;setBusy(true);try{await finishGroupedOperation(token,groupId,note);await onRefresh();setMessage("Grupo finalizado e tempo rateado entre as OPs.");setGroupId(null);setIds([]);setCode("");setNote("")}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível finalizar.")}finally{setBusy(false)}}
 function resume(group:typeof activeGroups[number]){const first=group.points[0].point;setIds(group.points.map(item=>item.order.id));setCode(group.code);setCriterion((first.criterio_rateio as typeof criterion)||"metros");setQuantities(Object.fromEntries(group.points.map(item=>[item.order.id,Number(item.point.quantidade_rateio??0)])));setOperatorCode(profiles.find(p=>p.id===first.operador_id)?.nome??first.operador_id);setMachineCode(machines.find(m=>m.id===first.maquina_id)?.codigo??first.maquina_id);setGroupId(group.id);setMessage("Grupo em andamento carregado para finalização.")}
 useEffect(()=>{if(!groupId&&!ids.length&&activeGroups.length)resume(activeGroups[0])},[activeGroups.length]);
 const total=selected.reduce((sum,order)=>sum+quantity(order),0);
 return <div className="grouped-pointing"><div className="group-intro"><b>OPs agrupadas</b><span>Leia todas as OPs do mesmo lote físico.</span></div><div className="group-scan"><label>OP / QR CODE<input autoFocus value={scan} onChange={e=>setScan(e.target.value)} onKeyDown={key} disabled={!!groupId} placeholder="Bipe uma OP e pressione Enter"/></label><button onClick={add} disabled={!!groupId}>Adicionar</button></div><div className="group-orders">{selected.map(order=><article key={order.id}><div><b>OP {order.numero_op}</b><ArticleLabel code={order.codigo_artigo} name={order.artigo}/></div><label>{criterion.toUpperCase()}<input type="number" min="0.001" step="0.001" disabled={!!groupId} value={quantity(order)} onChange={e=>setQuantities(current=>({...current,[order.id]:Number(e.target.value)}))}/></label><button disabled={!!groupId} onClick={()=>{setIds(current=>current.filter(id=>id!==order.id));setCode("")}}>×</button></article>)}</div>{selected.length>0&&<><div className="group-config"><label>CRITÉRIO DE RATEIO<select value={criterion} disabled={!!groupId} onChange={e=>{setCriterion(e.target.value as typeof criterion);setQuantities({})}}><option value="metros">Metros (recomendado)</option><option value="peso">Peso</option><option value="pecas">Peças</option></select></label><label>OPERAÇÃO COMUM<select value={code} disabled={!!groupId} onChange={e=>setCode(e.target.value)}><option value="">Selecione</option>{common.map(op=><option key={op.codigo} value={op.codigo}>{op.codigo} · {op.descricao}</option>)}</select></label><label>OPERADOR / CRACHÁ<input list="group-operators" value={operatorCode} disabled={!!groupId} onChange={e=>setOperatorCode(e.target.value)}/><datalist id="group-operators">{profiles.map(p=><option key={p.id} value={p.nome}/>)}</datalist></label><label>MÁQUINA / CÓDIGO<input list="group-machines" value={machineCode} disabled={!!groupId} onChange={e=>setMachineCode(e.target.value)}/><datalist id="group-machines">{machines.map(m=><option key={m.id} value={m.codigo}>{m.nome}</option>)}</datalist></label></div><div className="group-summary"><span>{selected.length} OPs</span><span>Total: {total.toLocaleString("pt-BR")} {criterion}</span><span>Rateio automático ao finalizar</span></div><label className="group-note">OBSERVAÇÃO<textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="Opcional"/></label></>}{message&&<p className="pointing-message">{message}</p>}<button className={groupId?"finish-action":"start-action"} disabled={busy||(!groupId&&selected.length<2)} onClick={groupId?finish:start}>{busy?"Registrando…":groupId?"■ FINALIZAR GRUPO E RATEAR TEMPO":"▶ INICIAR APONTAMENTO AGRUPADO"}</button></div>
}
