"use client";
import {useEffect,useState} from "react";
import {Maquina,Ordem,Perfil,resumeGroupedOperation} from "./supabase";
import {formatDuration,formatSeconds} from "./duration";
import {formatFactoryDateTime} from "./factory-time";
import {ArticleLabel} from "./article-label";
const reasonLabel:Record<string,string>={normal:"Execução concluída",pausa:"Pausa",fim_turno:"Fim do turno",retrabalho:"Retrabalho",parada_maquina:"Parada de máquina"};
export function HistoryScreen({orders,profiles,machines,token,onClose,onResume}:{orders:Ordem[];profiles:Perfil[];machines:Maquina[];token:string;onClose:()=>void;onResume:()=>Promise<void>}){
 const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 const [resuming,setResuming]=useState<string|null>(null),[message,setMessage]=useState("");
 const rows=orders.flatMap(order=>(order.operacoes??[]).flatMap(operation=>(operation.apontamentos??[]).map(point=>({order,operation,point})))).sort((a,b)=>b.point.inicio_em.localeCompare(a.point.inicio_em));
 const resumable=new Set(["pausa","fim_turno","parada_maquina"]);const shownGroups=new Set<string>();
 async function resume(groupId:string){setResuming(groupId);setMessage("");try{await resumeGroupedOperation(token,groupId);await onResume()}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível retomar o grupo.");setResuming(null)}}
 const fmt=(value:string|null)=>formatFactoryDateTime(value,"Em andamento");
 return <section className="manage-screen history-screen"><header><div><p className="eyebrow">PRODUÇÃO</p><h2>Histórico de execuções</h2></div><button onClick={onClose}>×</button></header>{message&&<p className="pointing-message history-message">{message}</p>}<div className="table-wrap"><table><thead><tr><th>OP / ARTIGO / OPERAÇÃO</th><th>OPERADOR</th><th>MÁQUINA</th><th>INÍCIO</th><th>TÉRMINO</th><th>TEMPO</th><th>TIPO / OBSERVAÇÃO</th></tr></thead><tbody>{rows.map(({order,operation,point})=>{const showResume=!!point.grupo_id&&!!point.termino_em&&resumable.has(point.motivo_finalizacao??"")&&!shownGroups.has(point.grupo_id);if(point.grupo_id)shownGroups.add(point.grupo_id);return <tr key={point.id}><td><b>OP {order.numero_op}</b>{point.grupo_id&&<span className="group-badge">AGRUPADO</span>}<br/><ArticleLabel code={order.codigo_artigo} name={order.artigo}/><br/>{operation.codigo} · {operation.descricao}{point.grupo_id&&<small className="allocation-detail">Rateio: {Number(point.quantidade_rateio).toLocaleString("pt-BR")} {point.criterio_rateio}</small>}</td><td>{profiles.find(profile=>profile.id===point.operador_id)?.nome??"—"}</td><td>{machines.find(machine=>machine.id===point.maquina_id)?.codigo??"—"}</td><td>{fmt(point.inicio_em)}</td><td>{fmt(point.termino_em)}</td><td><b className={point.termino_em?"duration":"duration running"}>{point.duracao_rateada_segundos!=null?formatSeconds(point.duracao_rateada_segundos):formatDuration(point.inicio_em,point.termino_em,now)}</b>{point.grupo_id&&point.termino_em&&<small className="allocation-detail">tempo proporcional</small>}</td><td><span className="execution-type">{point.termino_em?(reasonLabel[point.motivo_finalizacao??"normal"]??"Execução concluída"):"Em andamento"}</span><br/>{point.observacao||"—"}{showResume&&<button className="resume-group" disabled={!!resuming} onClick={()=>resume(point.grupo_id!)}>{resuming===point.grupo_id?"Retomando…":"▶ Retomar grupo"}</button>}</td></tr>})}</tbody></table>{!rows.length&&<p className="pointing-empty">Nenhuma execução realizada.</p>}</div></section>
}
