"use client";
import {useEffect,useMemo,useState} from "react";
import {Maquina,Ordem,Perfil} from "./supabase";
import {dateRange,flattenExecutions,machineSeconds,machineState,MachineState} from "./machine-analytics";
import {formatFactoryDateTime} from "./factory-time";
import {formatSeconds} from "./duration";
import {ArticleLabel} from "./article-label";

const MONTHS=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const isoDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const monthBounds=(year:number,month:number)=>({from:isoDate(new Date(year,month,1)),to:isoDate(new Date(year,month+1,0))});
const stateLabel:Record<MachineState,string>={running:"Em andamento",stopped:"Parada",idle:"Sem apontamento"};

export function MachineDashboard({orders,machines,profiles,onRefresh,onClose}:{orders:Ordem[];machines:Maquina[];profiles:Perfil[];onRefresh:()=>Promise<void>;onClose:()=>void}){
 const today=new Date(),[month,setMonth]=useState(today.getMonth()),[year,setYear]=useState(today.getFullYear());const initial=monthBounds(today.getFullYear(),today.getMonth());
 const [from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[machineId,setMachineId]=useState("all"),[status,setStatus]=useState<"all"|MachineState>("all"),[search,setSearch]=useState(""),[refreshing,setRefreshing]=useState(false),[updated,setUpdated]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>refresh(),60000);return()=>clearInterval(timer)},[]);
 async function refresh(){setRefreshing(true);try{await onRefresh();setUpdated(Date.now())}finally{setRefreshing(false)}}
 function selectMonth(nextMonth:number,nextYear=year){setMonth(nextMonth);setYear(nextYear);const range=monthBounds(nextYear,nextMonth);setFrom(range.from);setTo(range.to)}
 const executions=useMemo(()=>flattenExecutions(orders),[orders]);const period=dateRange(from,to);const selectedMonth=dateRange(monthBounds(year,month).from,monthBounds(year,month).to);const day=dateRange(isoDate(today),isoDate(today));
 const rows=machines.map(machine=>{const live=machineState(executions,machine);const openOps=[...new Map(live.open.map(item=>[item.order.id,item])).values()];return{machine,live,openOps,today:machineSeconds(executions,machine.id,day.start,day.end),monthly:machineSeconds(executions,machine.id,selectedMonth.start,selectedMonth.end),period:machineSeconds(executions,machine.id,period.start,period.end)}});
 const term=search.trim().toLocaleUpperCase("pt-BR");const filtered=rows.filter(row=>(machineId==="all"||row.machine.id===machineId)&&(status==="all"||row.live.state===status)&&(!term||[row.machine.codigo,row.machine.nome,row.machine.setor,...row.openOps.flatMap(item=>[item.order.numero_op,item.order.codigo_artigo??"",item.order.artigo,item.operation.descricao])].join(" ").toLocaleUpperCase("pt-BR").includes(term)));
 const running=rows.filter(row=>row.live.state==="running").length,stopped=rows.filter(row=>row.live.state==="stopped").length,idle=rows.length-running-stopped,totalPeriod=rows.reduce((sum,row)=>sum+row.period,0);
 return <section className="machine-dashboard"><header className="manager-head"><div><p className="eyebrow">GESTÃO EM TEMPO REAL</p><h2>Painel de máquinas</h2><p>Foto atual da produção e horas apontadas por equipamento.</p></div><div><small>Atualizado {new Date(updated).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small><button className="refresh-dashboard" disabled={refreshing} onClick={refresh}>{refreshing?"Atualizando…":"↻ Atualizar agora"}</button><button className="dashboard-close" onClick={onClose} aria-label="Fechar">×</button></div></header>
 <div className="manager-kpis"><button onClick={()=>setStatus("all")} className={status==="all"?"active":""}><small>Máquinas cadastradas</small><strong>{rows.length}</strong><span>Visão completa</span></button><button onClick={()=>setStatus("running")} className={`green ${status==="running"?"active":""}`}><small>Em andamento</small><strong>{running}</strong><span>Com OP aberta agora</span></button><button onClick={()=>setStatus("stopped")} className={`red ${status==="stopped"?"active":""}`}><small>Paradas</small><strong>{stopped}</strong><span>Pausa ou parada registrada</span></button><button onClick={()=>setStatus("idle")} className={`red ${status==="idle"?"active":""}`}><small>Sem apontamento</small><strong>{idle}</strong><span>Sem execução aberta</span></button><article><small>Horas no período</small><strong>{formatSeconds(totalPeriod)}</strong><span>{from.split("-").reverse().join("/")} a {to.split("-").reverse().join("/")}</span></article></div>
 <div className="manager-filters"><label className="manager-search">PESQUISAR<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Máquina, setor, OP, artigo ou operação"/></label><label>MÊS<select value={month} onChange={event=>selectMonth(Number(event.target.value))}>{MONTHS.map((name,index)=><option value={index} key={name}>{name}</option>)}</select></label><label>ANO<select value={year} onChange={event=>selectMonth(month,Number(event.target.value))}>{Array.from({length:6},(_,index)=>today.getFullYear()-4+index).map(value=><option key={value}>{value}</option>)}</select></label><label>DE<input type="date" value={from} max={to} onChange={event=>setFrom(event.target.value)}/></label><label>ATÉ<input type="date" value={to} min={from} onChange={event=>setTo(event.target.value)}/></label><label>MÁQUINA<select value={machineId} onChange={event=>setMachineId(event.target.value)}><option value="all">Todas</option>{machines.map(machine=><option key={machine.id} value={machine.id}>{machine.codigo} · {machine.nome}</option>)}</select></label></div>
 <div className="machine-grid">{filtered.map(({machine,live,openOps,today:todaySeconds,monthly,period:periodSeconds})=><article className={`machine-card ${live.state}`} key={machine.id}><div className="machine-card-head"><div><small>{machine.setor||"SETOR NÃO INFORMADO"}</small><h3>{machine.codigo}</h3><p>{machine.nome}</p></div><span className={`machine-state ${live.state}`}>{stateLabel[live.state]}</span></div><div className="machine-hours"><div><small>HOJE</small><b>{formatSeconds(todaySeconds)}</b></div><div><small>{MONTHS[month].toLocaleUpperCase("pt-BR")}</small><b>{formatSeconds(monthly)}</b></div><div><small>PERÍODO</small><b>{formatSeconds(periodSeconds)}</b></div></div>{openOps.length?<div className="machine-current"><small>RODANDO AGORA</small>{openOps.map(item=><div key={item.point.id}><b>OP {item.order.numero_op}</b><ArticleLabel code={item.order.codigo_artigo} name={item.order.artigo}/><span>{item.operation.codigo} · {item.operation.descricao}</span><em>{profiles.find(profile=>profile.id===item.point.operador_id)?.nome??"Operador não identificado"} · desde {formatFactoryDateTime(item.point.inicio_em)}</em></div>)}</div>:<div className="machine-empty"><b>{live.state==="stopped"?"Produção interrompida":"Nenhuma OP rodando"}</b><span>{live.latest?`Último registro: ${formatFactoryDateTime(live.latest.point.termino_em)}`:"Ainda não existem apontamentos nesta máquina."}</span>{live.state==="stopped"&&<em>{live.latest?.point.motivo_finalizacao==="parada_maquina"?"Parada de máquina":"Pausa"}</em>}</div>}</article>)}</div>{!filtered.length&&<div className="pointing-empty">Nenhuma máquina corresponde aos filtros informados.</div>}</section>
}
