"use client";
import {useMemo,useState} from "react";
import {Maquina,Ordem,Perfil} from "./supabase";
import {ArticleLabel} from "./article-label";
type Props={orders:Ordem[];profiles:Perfil[];machines:Maquina[];onRefresh:()=>Promise<void>;onClose:()=>void};
type Situation="all"|"open"|"waiting"|"running"|"finished";
const norm=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleUpperCase("pt-BR").trim();
export function OrdersScreen({orders,profiles,machines,onRefresh,onClose}:Props){
 const [search,setSearch]=useState(""),[machineId,setMachineId]=useState(""),[situation,setSituation]=useState<Situation>("all"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[refreshing,setRefreshing]=useState(false);
 const enriched=useMemo(()=>orders.map(order=>{const operations=[...(order.operacoes??[])].sort((a,b)=>a.sequencia-b.sequencia);const points=operations.flatMap(operation=>(operation.apontamentos??[]).map(point=>({operation,point})));const open=points.find(item=>!item.point.termino_em);const latest=[...points].sort((a,b)=>b.point.inicio_em.localeCompare(a.point.inicio_em))[0];const covered=operations.filter(operation=>operation.apontamentos?.some(point=>point.termino_em)).length;return{order,operations,open,latest,machineIds:[...new Set(points.map(item=>item.point.maquina_id))],progress:operations.length?Math.round(covered/operations.length*100):0}}),[orders]);
 const filtered=useMemo(()=>{const term=norm(search);return enriched.filter(item=>{const {order,open,machineIds}=item;const machineText=machines.filter(machine=>machineIds.includes(machine.id)).flatMap(machine=>[machine.codigo,machine.nome]);const searchable=norm([order.numero_op,order.codigo_artigo,order.artigo,order.cliente,...machineText].join(" "));const date=order.data_op??"";const closed=!!order.encerrada_em;const situationOk=situation==="all"||(situation==="open"&&!!open)||(situation==="finished"&&closed)||(situation==="running"&&!closed&&order.status==="em_producao")||(situation==="waiting"&&!closed&&order.status==="aguardando");return(!term||searchable.includes(term))&&(!machineId||machineIds.includes(machineId))&&situationOk&&(!from||date>=from)&&(!to||date<=to)})},[enriched,search,machineId,situation,from,to,machines]);
 const openCount=enriched.filter(item=>item.open).length,finishedCount=enriched.filter(item=>item.order.encerrada_em).length,runningCount=enriched.filter(item=>!item.order.encerrada_em&&item.order.status==="em_producao").length;
 async function refresh(){setRefreshing(true);try{await onRefresh()}finally{setRefreshing(false)}}
 function clear(){setSearch("");setMachineId("");setSituation("all");setFrom("");setTo("")}
 return <section className="orders-screen"><header><div><p className="eyebrow">CONTROLE DA PRODUÇÃO</p><h2>Ordens de produção</h2><p>Consulte o andamento, os apontamentos abertos e as OPs encerradas.</p></div><div><button className="refresh-orders" onClick={refresh} disabled={refreshing}>{refreshing?"Atualizando…":"↻ Atualizar"}</button><button className="close-orders" onClick={onClose}>×</button></div></header>
 <div className="orders-kpis"><button className={situation==="all"?"active":""} onClick={()=>setSituation("all")}><small>Total</small><b>{orders.length}</b></button><button className={situation==="running"?"active":""} onClick={()=>setSituation("running")}><small>Em produção</small><b>{runningCount}</b></button><button className={situation==="open"?"active alert":"alert"} onClick={()=>setSituation("open")}><small>Apontamento aberto</small><b>{openCount}</b></button><button className={situation==="finished"?"active done":"done"} onClick={()=>setSituation("finished")}><small>OPs encerradas</small><b>{finishedCount}</b></button></div>
 <div className="orders-filters"><label className="order-search">PESQUISAR<input autoFocus value={search} onChange={event=>setSearch(event.target.value)} placeholder="Número da OP, código, artigo, cliente ou máquina"/></label><label>MÁQUINA<select value={machineId} onChange={event=>setMachineId(event.target.value)}><option value="">Todas</option>{machines.map(machine=><option key={machine.id} value={machine.id}>{machine.codigo} · {machine.nome}</option>)}</select></label><label>SITUAÇÃO<select value={situation} onChange={event=>setSituation(event.target.value as Situation)}><option value="all">Todas</option><option value="open">Com apontamento aberto</option><option value="running">Em produção</option><option value="waiting">Aguardando</option><option value="finished">Encerradas</option></select></label><label>DATA OP — DE<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>ATÉ<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button className="clear-filters" onClick={clear}>Limpar filtros</button></div>
 <div className="orders-result"><span><b>{filtered.length}</b> OP{filtered.length===1?"":"s"} encontrada{filtered.length===1?"":"s"}</span>{(search||machineId||situation!=="all"||from||to)&&<em>Filtros ativos</em>}</div>
 <div className="orders-list">{filtered.map(({order,operations,open,latest,progress})=>{const active=open??latest;const machine=machines.find(item=>item.id===active?.point.maquina_id);const operator=profiles.find(item=>item.id===active?.point.operador_id);return <article key={order.id} className={open?"has-open":order.encerrada_em?"is-finished":""}><div className="order-main"><div className="order-ident"><div><b>OP {order.numero_op}</b><span className={`order-state ${open?"open":order.status}`}>{open?"Apontamento aberto":order.encerrada_em?"Encerrada":order.status==="em_producao"?"Em produção":"Aguardando"}</span></div><ArticleLabel code={order.codigo_artigo} name={order.artigo}/><small>{order.cliente} · Data OP: {order.data_op?new Date(`${order.data_op}T12:00:00`).toLocaleDateString("pt-BR"):"não informada"}</small></div><div className="order-qty"><span><small>PEÇAS</small><b>{order.pecas??0}</b></span><span><small>METROS</small><b>{Number(order.metros??0).toLocaleString("pt-BR")}</b></span><span><small>PESO</small><b>{Number(order.peso??0).toLocaleString("pt-BR")}</b></span></div><div className="order-progress"><span><b>{progress}%</b><small>{operations.filter(op=>op.apontamentos?.some(point=>point.termino_em)).length}/{operations.length} com apontamento</small></span><i><u style={{width:`${progress}%`}}/></i></div><div className="order-current"><small>{open?"EM EXECUÇÃO":"ÚLTIMA / PRÓXIMA OPERAÇÃO"}</small><b>{active?`${active.operation.codigo} · ${active.operation.descricao}`:"Fluxo não cadastrado"}</b><span>{machine?`${machine.codigo} · ${machine.nome}`:"Máquina não informada"} · {operator?.nome??"Operador não informado"}</span>{open&&<time>Início: {new Date(open.point.inicio_em).toLocaleString("pt-BR")}</time>}</div></div><div className="order-flow">{operations.map(operation=>{const count=operation.apontamentos?.filter(point=>point.termino_em).length??0;return <span key={operation.id} className={operation.status}><b>{operation.codigo}</b>{operation.descricao}<small>{operation.status==="em_andamento"?"Em andamento":count?`Contém ${count} apontamento${count===1?"":"s"}`:"Sem apontamento"}</small></span>})}</div></article>})}{!filtered.length&&<div className="orders-empty"><b>Nenhuma OP encontrada</b><span>Revise os filtros ou limpe a pesquisa.</span><button onClick={clear}>Limpar filtros</button></div>}</div></section>
}
