"use client";
import {useEffect,useMemo,useState} from "react";
import {changePointOperator,finishOperation,Maquina,Ordem,Perfil,startOperation} from "./supabase";
import {formatFactoryDateTime} from "./factory-time";
import {parseOperationScan,parseOpScan} from "./scanner";
import {ArticleLabel} from "./article-label";
import {GroupedPointing} from "./grouped-pointing";
type Props={orders:Ordem[];profiles:Perfil[];machines:Maquina[];token:string;userId:string;onRefresh:()=>Promise<void>;onClose:()=>void};
const norm=(value:string)=>value.trim().toLocaleUpperCase("pt-BR");
const reasons=[['normal','Finalizar execução'],['pausa','Pausar'],['fim_turno','Fim do turno'],['retrabalho','Retrabalho'],['parada_maquina','Parada de máquina']];
export function PointingScreen({orders,profiles,machines,token,userId,onRefresh,onClose}:Props){
 const [grouped,setGrouped]=useState(false),[number,setNumber]=useState(""),[operationCode,setOperationCode]=useState(""),[operatorCode,setOperatorCode]=useState(profiles.find(p=>p.id===userId)?.nome??""),[machineCode,setMachineCode]=useState(""),[note,setNote]=useState(""),[reason,setReason]=useState("normal"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const order=useMemo(()=>orders.find(item=>item.numero_op===parseOpScan(number)),[orders,number]);
 const operations=useMemo(()=>[...(order?.operacoes??[])].sort((a,b)=>a.sequencia-b.sequencia),[order]);
 const selected=operations.find(operation=>operation.codigo.padStart(4,"0")===parseOperationScan(operationCode));
 const openPoint=selected?.apontamentos?.find(point=>!point.termino_em);
 const executions=selected?.apontamentos?.filter(point=>point.termino_em).length??0;
 const operator=profiles.find(profile=>norm(profile.nome)===norm(operatorCode)||profile.id===operatorCode.trim());
 const machine=machines.find(item=>norm(item.codigo)===norm(machineCode)||norm(item.nome)===norm(machineCode)||item.id===machineCode.trim());
 useEffect(()=>{setOperationCode("");setMachineCode("");setMessage("")},[order?.id]);
 useEffect(()=>{if(openPoint){setOperatorCode(profiles.find(p=>p.id===openPoint.operador_id)?.nome??openPoint.operador_id);setMachineCode(machines.find(m=>m.id===openPoint.maquina_id)?.codigo??openPoint.maquina_id)}else setMachineCode("")},[openPoint?.id,profiles,machines]);
 async function act(){if(!selected)return;if(order?.encerrada_em){setMessage("Esta OP está encerrada e não aceita novos apontamentos.");return}setBusy(true);setMessage("");try{if(!openPoint){if(!operator||!machine)throw new Error("Leia ou selecione um operador e uma máquina válidos.");await startOperation(token,selected.id,operator.id,machine.id,note)}else{if(openPoint.grupo_id)throw new Error("Este apontamento pertence a um grupo. Finalize pelo modo OPs agrupadas.");if(!operator)throw new Error("Leia ou selecione um operador válido.");if(operator.id!==openPoint.operador_id)await changePointOperator(token,openPoint.id,operator.id);await finishOperation(token,selected.id,note,reason)}await onRefresh();setNote("");setReason("normal");setMessage(openPoint?"Execução finalizada. A operação continua disponível.":"Nova execução iniciada.")}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível registrar.")}finally{setBusy(false)}}
 return <section className="pointing-screen"><div className="pointing-top"><div><p className="eyebrow">APONTAMENTO RÁPIDO · MODO PILOTO</p><h2>Registrar produção</h2><p>Cada retomada ou retrabalho gera uma nova execução no histórico.</p></div><button onClick={onClose}>×</button></div><label className="pointing-mode"><input type="checkbox" checked={grouped} onChange={event=>setGrouped(event.target.checked)}/><span><b>OPs agrupadas</b><small>Uma execução física para duas ou mais OPs, com rateio proporcional.</small></span></label>
 {grouped?<GroupedPointing orders={orders} profiles={profiles} machines={machines} token={token} userId={userId} onRefresh={onRefresh}/>:<><label className="scan-input">OP / QR CODE<input autoFocus value={number} onChange={event=>setNumber(event.target.value)} placeholder="Escaneie ou digite a OP"/><span>⌗</span></label>{!order?<div className="pointing-empty">Aguardando leitura de uma OP cadastrada.</div>:<><div className={`pointing-order ${order.encerrada_em?"closed":""}`}><div><small>ORDEM DE PRODUÇÃO</small><strong>OP {order.numero_op}</strong><ArticleLabel code={order.codigo_artigo} name={order.artigo}/></div><em>{order.encerrada_em?"ENCERRADA":"ATIVA"}</em></div>
 {order.encerrada_em?<div className="pointing-empty closed-warning">OP encerrada pelo administrador em {formatFactoryDateTime(order.encerrada_em)}.<br/>{order.motivo_encerramento}</div>:<><label className="operation-scan">OPERAÇÃO / QR CODE<input list="operations" value={operationCode} onChange={event=>setOperationCode(event.target.value)} placeholder="Leia ou selecione uma operação"/><datalist id="operations">{operations.map(operation=><option key={operation.id} value={operation.codigo}>{operation.descricao}</option>)}</datalist></label><div className="flow-strip">{operations.map(operation=>{const count=operation.apontamentos?.filter(point=>point.termino_em).length??0;return <button type="button" key={operation.id} onClick={()=>setOperationCode(operation.codigo)} className={operation.id===selected?.id?"current":operation.status==="em_andamento"?"running":""}><b>{operation.codigo}</b><span>{operation.descricao}</span><small>{operation.status==="em_andamento"?"Em andamento":count?`Executada ${count} vez${count===1?"":"es"}`:"Nunca apontada"}</small></button>})}</div>
 {!selected?<div className="pointing-empty compact">Escolha qualquer operação do fluxo.</div>:<div className="pointing-form"><div className="current-operation"><small>OPERAÇÃO SELECIONADA · {executions} EXECUÇÃO{executions===1?"":"ÕES"} ANTERIOR{executions===1?"":"ES"}</small><strong>{selected.codigo} · {selected.descricao}</strong>{openPoint&&<span>Em andamento desde {formatFactoryDateTime(openPoint.inicio_em)}</span>}</div><div className="pointing-fields"><label>OPERADOR / CRACHÁ<input list="operators" value={operatorCode} onChange={event=>setOperatorCode(event.target.value)} placeholder="Leia ou selecione"/><datalist id="operators">{profiles.map(profile=><option key={profile.id} value={profile.nome}/>)}</datalist></label><label>MÁQUINA / CÓDIGO<input list="machines" value={machineCode} onChange={event=>setMachineCode(event.target.value)} disabled={!!openPoint} placeholder="Leia ou selecione"/><datalist id="machines">{machines.map(item=><option key={item.id} value={item.codigo}>{item.nome}</option>)}</datalist></label>{openPoint&&<label className="finish-reason">MOTIVO DO ENCERRAMENTO<select value={reason} onChange={event=>setReason(event.target.value)}>{reasons.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}<label className="note">OBSERVAÇÃO<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Opcional" rows={2}/></label></div>{message&&<p className="pointing-message">{message}</p>}<button className={openPoint?"finish-action":"start-action"} disabled={busy} onClick={act}>{busy?"Registrando…":openPoint?"■ FINALIZAR ESTA EXECUÇÃO":"▶ INICIAR NOVA EXECUÇÃO"}</button></div>}</>}</>}</>}</section>
}
