"use client";
import {useMemo,useState} from "react";
import {finishOperation,Maquina,Ordem,Perfil,startOperation} from "./supabase";
type Props={orders:Ordem[];profiles:Perfil[];machines:Maquina[];token:string;userId:string;onRefresh:()=>Promise<void>;onClose:()=>void};
const norm=(v:string)=>v.trim().toLocaleUpperCase("pt-BR");
export function PointingScreen({orders,profiles,machines,token,userId,onRefresh,onClose}:Props){
 const [number,setNumber]=useState("");const initial=profiles.find(p=>p.id===userId);const [operatorCode,setOperatorCode]=useState(initial?.nome??"");const [machineCode,setMachineCode]=useState("");const [note,setNote]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const order=useMemo(()=>orders.find(o=>o.numero_op===number.trim()),[orders,number]);const operations=[...(order?.operacoes??[])].sort((a,b)=>a.sequencia-b.sequencia);const current=operations.find(o=>o.status==="em_andamento")??operations.find(o=>o.status==="liberada");const openPoint=current?.apontamentos?.find(a=>!a.termino_em);const operator=profiles.find(p=>norm(p.nome)===norm(operatorCode)||p.id===operatorCode.trim());const machine=machines.find(m=>norm(m.codigo)===norm(machineCode)||norm(m.nome)===norm(machineCode)||m.id===machineCode.trim());
 async function act(kind:"start"|"finish"){if(!current)return;setBusy(true);setMessage("");try{if(kind==="start"){if(!operator||!machine)throw new Error("Leia ou selecione um operador e uma máquina válidos.");await startOperation(token,current.id,operator.id,machine.id,note)}else await finishOperation(token,current.id,note);await onRefresh();setNote("");setMessage(kind==="start"?"Operação iniciada. Data e hora registradas automaticamente.":"Operação finalizada. A próxima etapa foi liberada.")}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível registrar.")}finally{setBusy(false)}}
 return <section className="pointing-screen"><div className="pointing-top"><div><p className="eyebrow">APONTAMENTO RÁPIDO</p><h2>Registrar produção</h2><p>Leia o QR Code/código de barras ou informe os dados.</p></div><button onClick={onClose}>×</button></div><label className="scan-input">OP / QR CODE<input autoFocus inputMode="numeric" value={number} onChange={e=>setNumber(e.target.value.replace(/\D/g,""))} placeholder="Escaneie ou digite a OP"/><span>⌗</span></label>{!order?<div className="pointing-empty">Aguardando leitura de uma OP cadastrada.</div>:<><div className="pointing-order"><div><small>ORDEM DE PRODUÇÃO</small><strong>OP {order.numero_op}</strong><span>{order.artigo}</span></div><em>{operations.filter(o=>o.status==="finalizada").length}/{operations.length} etapas</em></div><div className="flow-strip">{operations.map(o=><div key={o.id} className={o.id===current?.id?"current":o.status==="finalizada"?"done":""}><b>{o.codigo}</b><span>{o.descricao}</span><small>{o.status==="finalizada"?"Concluída":o.id===current?.id?(openPoint?"Em andamento":"Liberada"):"Aguardando"}</small></div>)}</div>{!current?<div className="pointing-empty success">✓ Todas as operações foram concluídas.</div>:<div className="pointing-form"><div className="current-operation"><small>OPERAÇÃO ATUAL</small><strong>{current.codigo} · {current.descricao}</strong>{openPoint&&<span>Iniciada em {new Date(openPoint.inicio_em).toLocaleString("pt-BR")}</span>}</div><div className="pointing-fields"><label>OPERADOR / CRACHÁ<input list="operators" value={operatorCode} onChange={e=>setOperatorCode(e.target.value)} disabled={!!openPoint} placeholder="Leia o crachá ou selecione"/><datalist id="operators">{profiles.map(p=><option key={p.id} value={p.nome}/>)}</datalist></label><label>MÁQUINA / CÓDIGO<input list="machines" value={machineCode} onChange={e=>setMachineCode(e.target.value)} disabled={!!openPoint} placeholder="Leia o código ou selecione"/><datalist id="machines">{machines.map(m=><option key={m.id} value={m.codigo}>{m.nome}</option>)}</datalist></label><label className="note">OBSERVAÇÃO<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Opcional" rows={2}/></label></div>{message&&<p className="pointing-message">{message}</p>}<button className={openPoint?"finish-action":"start-action"} disabled={busy} onClick={()=>act(openPoint?"finish":"start")}>{busy?"Registrando…":openPoint?"■ FINALIZAR OPERAÇÃO":"▶ INICIAR OPERAÇÃO"}</button></div>}</>}</section>}
